version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: conf/Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - .:/var/www/
      - ./conf/conf.d:/etc/nginx/conf.d/
    ports:
      - 80:80
    networks:
      - backend

  mysql:
    platform: linux/x86_64
    image: mysql
    tty: true
    container_name: mysql
    restart: always
    ports:
      - 8889:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  db:
