<?php

return [
    'AF' => ['name' => 'Afghanistan', 'phone_code' => '+93', 'nationality' => 'Afghan', 'language' => 'Uzbek'],
    'AL' => ['name' => 'Albania', 'phone_code' => '+355', 'nationality' => 'Albanian', 'language' => 'Albanian'],
    'DZ' => ['name' => 'Algeria', 'phone_code' => '+213', 'nationality' => 'Algerian', 'language' => 'Arabic'],
    'AS' => ['name' => 'American Samoa', 'phone_code' => '+1684', 'nationality' => 'American Samoan', 'language' => 'English'],
    'AD' => ['name' => 'Andorra', 'phone_code' => '+376', 'nationality' => 'Andorran', 'language' => 'English'],
    'AO' => ['name' => 'Angola', 'phone_code' => '+244', 'nationality' => 'Angolan', 'language' => 'Portuguese'],
    'AI' => ['name' => 'Anguilla', 'phone_code' => '+1264', 'nationality' => 'Anguillan', 'language' => 'Spanish'],
    'AG' => ['name' => 'Antigua And Barbuda', 'phone_code' => '+1268', 'nationality' => 'Antiguan or Barbudan', 'language' => 'Spanish'],
    'AR' => ['name' => 'Argentina', 'phone_code' => '+54', 'nationality' => 'Argentine', 'language' => 'Spanish'],
    'AM' => ['name' => 'Armenia', 'phone_code' => '+374', 'nationality' => 'Armenian', 'language' => 'Armenian'],
    'AW' => ['name' => 'Aruba', 'phone_code' => '+297', 'nationality' => 'Aruban', 'language' => 'Dutch'],
    'AU' => ['name' => 'Australia', 'phone_code' => '+61', 'nationality' => 'Australian', 'language' => 'English'],
    'AT' => ['name' => 'Austria', 'phone_code' => '+43', 'nationality' => 'Austrian', 'language' => 'English'],
    'AZ' => ['name' => 'Azerbaijan', 'phone_code' => '+994', 'nationality' => 'Azerbaijani, Azeri', 'language' => 'Azerbaijani'],
    'BS' => ['name' => 'Bahamas The', 'phone_code' => '+1242', 'nationality' => 'Bahamian', 'language' => 'English'],
    'BH' => ['name' => 'Bahrain', 'phone_code' => '+973', 'nationality' => 'Bahraini', 'language' => 'Arabic'],
    'BD' => ['name' => 'Bangladesh', 'phone_code' => '+880', 'nationality' => 'Bangladeshi', 'language' => 'Bangla'],
    'BB' => ['name' => 'Barbados', 'phone_code' => '+1246', 'nationality' => 'Barbadian', 'language' => 'Spanish'],
    'BY' => ['name' => 'Belarus', 'phone_code' => '+375', 'nationality' => 'Belarusian', 'language' => 'Belarusian'],
    'BE' => ['name' => 'Belgium', 'phone_code' => '+32', 'nationality' => 'Belgian', 'language' => 'Walloon'],
    'BZ' => ['name' => 'Belize', 'phone_code' => '+501', 'nationality' => 'Belizean', 'language' => 'Spanish'],
    'BJ' => ['name' => 'Benin', 'phone_code' => '+229', 'nationality' => 'Beninese, Beninois', 'language' => 'Yoruba'],
    'BM' => ['name' => 'Bermuda', 'phone_code' => '+1441', 'nationality' => 'Bermudian, Bermudan', 'language' => 'Spanish'],
    'BT' => ['name' => 'Bhutan', 'phone_code' => '+975', 'nationality' => 'Bhutanese', 'language' => 'Dzongkha'],
    'BO' => ['name' => 'Bolivia', 'phone_code' => '+591', 'nationality' => 'Bolivian', 'language' => 'Quechua'],
    'BA' => ['name' => 'Bosnia and Herzegovina', 'phone_code' => '+387', 'nationality' => 'Bosnian or Herzegovinian', 'language' => 'Bosnian'],
    'BW' => ['name' => 'Botswana', 'phone_code' => '+267', 'nationality' => 'Motswana, Botswanan', 'language' => 'Tswana'],
    'BV' => ['name' => 'Bouvet Island', 'phone_code' => '+0', 'nationality' => 'Bouvet Island', 'language' => 'English'],
    'BR' => ['name' => 'Brazil', 'phone_code' => '+55', 'nationality' => 'Brazilian', 'language' => 'English'],
    'IO' => ['name' => 'British Indian Ocean Territory', 'phone_code' => '+246', 'nationality' => 'BIOT', 'language' => 'English'],
    'BN' => ['name' => 'Brunei', 'phone_code' => '+673', 'nationality' => 'Bruneian', 'language' => 'Malay'],
    'BG' => ['name' => 'Bulgaria', 'phone_code' => '+359', 'nationality' => 'Bulgarian', 'language' => 'Bulgarian'],
    'BF' => ['name' => 'Burkina Faso', 'phone_code' => '+226', 'nationality' => 'Burkinabé', 'language' => 'French'],
    'BI' => ['name' => 'Burundi', 'phone_code' => '+257', 'nationality' => 'Burundian', 'language' => 'French'],
    'KH' => ['name' => 'Cambodia', 'phone_code' => '+855', 'nationality' => 'Cambodian', 'language' => 'Khmer'],
    'CM' => ['name' => 'Cameroon', 'phone_code' => '+237', 'nationality' => 'Cameroonian', 'language' => 'French'],
    'CA' => ['name' => 'Canada', 'phone_code' => '+1', 'nationality' => 'Canadian', 'language' => 'English'],
    'CV' => ['name' => 'Cape Verde', 'phone_code' => '+238', 'nationality' => 'Cape Verdenian', 'language' => 'Portuguese'],
    'KY' => ['name' => 'Cayman Islands', 'phone_code' => '+1345', 'nationality' => 'Caymanian', 'language' => 'Spanish'],
    'CF' => ['name' => 'Central African Republic', 'phone_code' => '+236', 'nationality' => 'Central African', 'language' => 'French'],
    'TD' => ['name' => 'Chad', 'phone_code' => '+235', 'nationality' => 'Chadian', 'language' => 'Arabic'],
    'CL' => ['name' => 'Chile', 'phone_code' => '+56', 'nationality' => 'Chilean', 'language' => 'English'],
    'CN' => ['name' => 'China', 'phone_code' => '+86', 'nationality' => 'Chinese', 'language' => 'Chinese'],
    'CX' => ['name' => 'Christmas Island', 'phone_code' => '+61', 'nationality' => 'Christmas Island', 'language' => 'English'],
    'CC' => ['name' => 'Cocos (Keeling) Islands', 'phone_code' => '+672', 'nationality' => 'Cocos Island', 'language' => 'English'],
    'CO' => ['name' => 'Colombia', 'phone_code' => '+57', 'nationality' => 'Colombian', 'language' => 'Spanish'],
    'KM' => ['name' => 'Comoros', 'phone_code' => '+269', 'nationality' => 'Comoran, Comorian', 'language' => 'Arabic'],
    'CG' => ['name' => 'Republic Of The Congo', 'phone_code' => '+242', 'nationality' => 'Congolese', 'language' => 'French'],
    'CD' => ['name' => 'Democratic Republic Of The Congo', 'phone_code' => '+242', 'nationality' => 'Congolese', 'language' => 'French'],
    'CK' => ['name' => 'Cook Islands', 'phone_code' => '+682', 'nationality' => 'Cook Island', 'language' => 'English'],
    'CR' => ['name' => 'Costa Rica', 'phone_code' => '+506', 'nationality' => 'Costa Rican', 'language' => 'Spanish'],
    'CI' => ['name' => 'Cote D Ivoire (Ivory Coast)', 'phone_code' => '+225', 'nationality' => 'Ivorian', 'language' => 'French'],
    'HR' => ['name' => 'Croatia (Hrvatska)', 'phone_code' => '+385', 'nationality' => 'Croatian', 'language' => 'English'],
    'CU' => ['name' => 'Cuba', 'phone_code' => '+53', 'nationality' => 'Cuban', 'language' => 'Spanish'],
    'CY' => ['name' => 'Cyprus', 'phone_code' => '+357', 'nationality' => 'Cypriot', 'language' => 'Turkish'],
    'CZ' => ['name' => 'Czech Republic', 'phone_code' => '+420', 'nationality' => 'Czech', 'language' => 'Czech'],
    'DK' => ['name' => 'Denmark', 'phone_code' => '+45', 'nationality' => 'Danish', 'language' => 'Danish'],
    'DJ' => ['name' => 'Djibouti', 'phone_code' => '+253', 'nationality' => 'Djiboutian', 'language' => 'Arabic'],
    'DM' => ['name' => 'Dominica', 'phone_code' => '+1767', 'nationality' => 'Dominican', 'language' => 'Spanish'],
    'DO' => ['name' => 'Dominican Republic', 'phone_code' => '+1809', 'nationality' => 'Dominican', 'language' => 'Spanish'],
    'TP' => ['name' => 'East Timor', 'phone_code' => '+670', 'nationality' => 'East Timor', 'language' => 'English'],
    'EC' => ['name' => 'Ecuador', 'phone_code' => '+593', 'nationality' => 'Ecuadorian', 'language' => 'Portuguese'],
    'EG' => ['name' => 'Egypt', 'phone_code' => '+20', 'nationality' => 'Egyptian', 'language' => 'Arabic'],
    'SV' => ['name' => 'El Salvador', 'phone_code' => '+503', 'nationality' => 'Salvadoran', 'language' => 'Spanish'],
    'GQ' => ['name' => 'Equatorial Guinea', 'phone_code' => '+240', 'nationality' => 'Equatorial Guinean, Equatoguinean', 'language' => 'French'],
    'ER' => ['name' => 'Eritrea', 'phone_code' => '+291', 'nationality' => 'Eritrean', 'language' => 'Arabic'],
    'EE' => ['name' => 'Estonia', 'phone_code' => '+372', 'nationality' => 'Estonian', 'language' => 'Estonian'],
    'ET' => ['name' => 'Ethiopia', 'phone_code' => '+251', 'nationality' => 'Ethiopian', 'language' => 'Somali'],
    'FK' => ['name' => 'Falkland Islands', 'phone_code' => '+500', 'nationality' => 'Falkland Island', 'language' => 'English'],
    'FO' => ['name' => 'Faroe Islands', 'phone_code' => '+298', 'nationality' => 'Faroese', 'language' => 'Faroese'],
    'FJ' => ['name' => 'Fiji Islands', 'phone_code' => '+679', 'nationality' => 'Fijian', 'language' => 'English'],
    'FI' => ['name' => 'Finland', 'phone_code' => '+358', 'nationality' => 'Finnish', 'language' => 'Swedish'],
    'FR' => ['name' => 'France', 'phone_code' => '+33', 'nationality' => 'French', 'language' => 'French'],
    'PF' => ['name' => 'French Polynesia', 'phone_code' => '+689', 'nationality' => 'French Polynesian', 'language' => 'French'],
    'GA' => ['name' => 'Gabon', 'phone_code' => '+241', 'nationality' => 'Gabonese', 'language' => 'French'],
    'GM' => ['name' => 'Gambia The', 'phone_code' => '+220', 'nationality' => 'Gambian', 'language' => 'English'],
    'GE' => ['name' => 'Georgia', 'phone_code' => '+995', 'nationality' => 'Georgian', 'language' => 'Georgian'],
    'DE' => ['name' => 'Germany', 'phone_code' => '+49', 'nationality' => 'German', 'language' => 'German'],
    'GH' => ['name' => 'Ghana', 'phone_code' => '+233', 'nationality' => 'Ghanaian', 'language' => 'English'],
    'GI' => ['name' => 'Gibraltar', 'phone_code' => '+350', 'nationality' => 'Gibraltar', 'language' => 'English'],
    'GR' => ['name' => 'Greece', 'phone_code' => '+30', 'nationality' => 'Greek, Hellenic', 'language' => 'Greek'],
    'GL' => ['name' => 'Greenland', 'phone_code' => '+299', 'nationality' => 'Greenlandic', 'language' => 'Spanish'],
    'GD' => ['name' => 'Grenada', 'phone_code' => '+1473', 'nationality' => 'Grenadian', 'language' => 'Spanish'],
    'GU' => ['name' => 'Guam', 'phone_code' => '+1671', 'nationality' => 'Guamanian, Guambat', 'language' => 'English'],
    'GT' => ['name' => 'Guatemala', 'phone_code' => '+502', 'nationality' => 'Guatemalan', 'language' => 'Spanish'],
    'XU' => ['name' => 'Guernsey and Alderney', 'phone_code' => '+44', 'nationality' => 'Channel Island', 'language' => 'English'],
    'GN' => ['name' => 'Guinea', 'phone_code' => '+224', 'nationality' => 'Guinean', 'language' => 'French'],
    'GW' => ['name' => 'Guinea-Bissau', 'phone_code' => '+245', 'nationality' => 'Bissau-Guinean', 'language' => 'French'],
    'GY' => ['name' => 'Guyana', 'phone_code' => '+592', 'nationality' => 'Guyanese', 'language' => 'English'],
    'HT' => ['name' => 'Haiti', 'phone_code' => '+509', 'nationality' => 'Haitian', 'language' => 'French'],
    'HN' => ['name' => 'Honduras', 'phone_code' => '+504', 'nationality' => 'Honduran', 'language' => 'Spanish'],
    'HK' => ['name' => 'Hong Kong S.A.R.', 'phone_code' => '+852', 'nationality' => 'Hong Kong, Hong Kongese', 'language' => 'Chinese'],
    'HU' => ['name' => 'Hungary', 'phone_code' => '+36', 'nationality' => 'Hungarian, Magyar', 'language' => 'Hungarian'],
    'IS' => ['name' => 'Iceland', 'phone_code' => '+354', 'nationality' => 'Icelandic', 'language' => 'English'],
    'IN' => ['name' => 'India', 'phone_code' => '+91', 'nationality' => 'Indian', 'language' => 'Hindi'],
    'ID' => ['name' => 'Indonesia', 'phone_code' => '+62', 'nationality' => 'Indonesian', 'language' => 'Indonesian'],
    'IR' => ['name' => 'Iran', 'phone_code' => '+98', 'nationality' => 'Iranian, Persian', 'language' => 'Arabic'],
    'IQ' => ['name' => 'Iraq', 'phone_code' => '+964', 'nationality' => 'Iraqi', 'language' => 'Arabic'],
    'IE' => ['name' => 'Ireland', 'phone_code' => '+353', 'nationality' => 'Irish', 'language' => 'Irish'],
    'IL' => ['name' => 'Israel', 'phone_code' => '+972', 'nationality' => 'Israeli', 'language' => 'Arabic'],
    'IT' => ['name' => 'Italy', 'phone_code' => '+39', 'nationality' => 'Italian', 'language' => 'Italian'],
    'JM' => ['name' => 'Jamaica', 'phone_code' => '+1876', 'nationality' => 'Jamaican', 'language' => 'English'],
    'JP' => ['name' => 'Japan', 'phone_code' => '+81', 'nationality' => 'Japanese', 'language' => 'Japanese'],
    'JO' => ['name' => 'Jordan', 'phone_code' => '+962', 'nationality' => 'Jordanian', 'language' => 'Arabic'],
    'KZ' => ['name' => 'Kazakhstan', 'phone_code' => '+7', 'nationality' => 'Kazakhstani, Kazakh', 'language' => 'Kazakh'],
    'KE' => ['name' => 'Kenya', 'phone_code' => '+254', 'nationality' => 'Kenyan', 'language' => 'English'],
    'KI' => ['name' => 'Kiribati', 'phone_code' => '+686', 'nationality' => 'I-Kiribati', 'language' => 'English'],
    'KP' => ['name' => 'Korea North', 'phone_code' => '+850', 'nationality' => 'North Korean', 'language' => 'Korean'],
    'KR' => ['name' => 'Korea South', 'phone_code' => '+82', 'nationality' => 'South Korean', 'language' => 'Korean'],
    'KW' => ['name' => 'Kuwait', 'phone_code' => '+965', 'nationality' => 'Kuwaiti', 'language' => 'Arabic'],
    'KG' => ['name' => 'Kyrgyzstan', 'phone_code' => '+996', 'nationality' => 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz', 'language' => 'Kyrgyz'],
    'LA' => ['name' => 'Laos', 'phone_code' => '+856', 'nationality' => 'Lao, Laotian', 'language' => 'Lao'],
    'LV' => ['name' => 'Latvia', 'phone_code' => '+371', 'nationality' => 'Latvian', 'language' => 'English'],
    'LB' => ['name' => 'Lebanon', 'phone_code' => '+961', 'nationality' => 'Lebanese', 'language' => 'Arabic'],
    'LS' => ['name' => 'Lesotho', 'phone_code' => '+266', 'nationality' => 'Basotho', 'language' => 'English'],
    'LR' => ['name' => 'Liberia', 'phone_code' => '+231', 'nationality' => 'Liberian', 'language' => 'English'],
    'LY' => ['name' => 'Libya', 'phone_code' => '+218', 'nationality' => 'Libyan', 'language' => 'Arabic'],
    'LI' => ['name' => 'Liechtenstein', 'phone_code' => '+423', 'nationality' => 'Liechtenstein', 'language' => 'German'],
    'LT' => ['name' => 'Lithuania', 'phone_code' => '+370', 'nationality' => 'Lithuanian', 'language' => 'Lithuanian'],
    'LU' => ['name' => 'Luxembourg', 'phone_code' => '+352', 'nationality' => 'Luxembourg, Luxembourgish', 'language' => 'Luxembourgish'],
    'MO' => ['name' => 'Macau S.A.R.', 'phone_code' => '+853', 'nationality' => 'Macanese, Chinese', 'language' => 'Chinese'],
    'MK' => ['name' => 'Macedonia', 'phone_code' => '+389', 'nationality' => 'Macedonian', 'language' => 'Macedonian'],
    'MG' => ['name' => 'Madagascar', 'phone_code' => '+261', 'nationality' => 'Malagasy', 'language' => 'English'],
    'MW' => ['name' => 'Malawi', 'phone_code' => '+265', 'nationality' => 'Malawian', 'language' => 'English'],
    'MY' => ['name' => 'Malaysia', 'phone_code' => '+60', 'nationality' => 'Malaysian', 'language' => 'Malay'],
    'MV' => ['name' => 'Maldives', 'phone_code' => '+960', 'nationality' => 'Maldivian', 'language' => 'English'],
    'ML' => ['name' => 'Mali', 'phone_code' => '+223', 'nationality' => 'Malian, Malinese', 'language' => 'French'],
    'MT' => ['name' => 'Malta', 'phone_code' => '+356', 'nationality' => 'Maltese', 'language' => 'English'],
    'XM' => ['name' => 'Man (Isle of)', 'phone_code' => '+44', 'nationality' => 'Man', 'language' => 'English'],
    'MH' => ['name' => 'Marshall Islands', 'phone_code' => '+692', 'nationality' => 'Marshallese', 'language' => 'English'],
    'MR' => ['name' => 'Mauritania', 'phone_code' => '+222', 'nationality' => 'Mauritanian', 'language' => 'French'],
    'MU' => ['name' => 'Mauritius', 'phone_code' => '+230', 'nationality' => 'Mauritian', 'language' => 'English'],
    'YT' => ['name' => 'Mayotte', 'phone_code' => '+269', 'nationality' => 'Mahoran', 'language' => 'English'],
    'MX' => ['name' => 'Mexico', 'phone_code' => '+52', 'nationality' => 'Mexican', 'language' => 'Spanish'],
    'FM' => ['name' => 'Micronesia', 'phone_code' => '+691', 'nationality' => 'Micronesian', 'language' => 'English'],
    'MD' => ['name' => 'Moldova', 'phone_code' => '+373', 'nationality' => 'Moldovan', 'language' => 'Romanian'],
    'MC' => ['name' => 'Monaco', 'phone_code' => '+377', 'nationality' => 'Monégasque, Monacan', 'language' => 'French'],
    'MN' => ['name' => 'Mongolia', 'phone_code' => '+976', 'nationality' => 'Mongolian', 'language' => 'Mongolian'],
    'MS' => ['name' => 'Montserrat', 'phone_code' => '+1664', 'nationality' => 'Montserratian', 'language' => 'English'],
    'MA' => ['name' => 'Morocco', 'phone_code' => '+212', 'nationality' => 'Moroccan', 'language' => 'Arabic'],
    'MZ' => ['name' => 'Mozambique', 'phone_code' => '+258', 'nationality' => 'Mozambican', 'language' => 'Portuguese'],
    'MM' => ['name' => 'Myanmar', 'phone_code' => '+95', 'nationality' => 'Burmese', 'language' => 'English'],
    'NA' => ['name' => 'Namibia', 'phone_code' => '+264', 'nationality' => 'Namibian', 'language' => 'English'],
    'NR' => ['name' => 'Nauru', 'phone_code' => '+674', 'nationality' => 'Nauruan', 'language' => 'English'],
    'NP' => ['name' => 'Nepal', 'phone_code' => '+977', 'nationality' => 'Nepali, Nepalese', 'language' => 'Nepali'],
    'AN' => ['name' => 'Netherlands Antilles', 'phone_code' => '+599', 'nationality' => 'Dutch, Netherlandic', 'language' => 'Dutch'],
    'NL' => ['name' => 'Netherlands The', 'phone_code' => '+31', 'nationality' => 'Dutch, Netherlandic', 'language' => 'Dutch'],
    'NZ' => ['name' => 'New Zealand', 'phone_code' => '+64', 'nationality' => 'New Zealand, NZ', 'language' => 'English'],
    'NI' => ['name' => 'Nicaragua', 'phone_code' => '+505', 'nationality' => 'Nicaraguan', 'language' => 'Spanish'],
    'NE' => ['name' => 'Niger', 'phone_code' => '+227', 'nationality' => 'Nigerien', 'language' => 'French'],
    'NG' => ['name' => 'Nigeria', 'phone_code' => '+234', 'nationality' => 'Nigerian', 'language' => 'English'],
    'NU' => ['name' => 'Niue', 'phone_code' => '+683', 'nationality' => 'Niuean', 'language' => 'English'],
    'NF' => ['name' => 'Norfolk Island', 'phone_code' => '+672', 'nationality' => 'Norfolk Island', 'language' => 'English'],
    'MP' => ['name' => 'Northern Mariana Islands', 'phone_code' => '+1670', 'nationality' => 'Northern Marianan', 'language' => 'English'],
    'NO' => ['name' => 'Norway', 'phone_code' => '+47', 'nationality' => 'Norwegian', 'language' => 'English'],
    'OM' => ['name' => 'Oman', 'phone_code' => '+968', 'nationality' => 'Omani', 'language' => 'Arabic'],
    'PK' => ['name' => 'Pakistan', 'phone_code' => '+92', 'nationality' => 'Pakistani', 'language' => 'Pashto'],
    'PW' => ['name' => 'Palau', 'phone_code' => '+680', 'nationality' => 'Palauan', 'language' => 'English'],
    'PS' => ['name' => 'Palestinian Territory Occupied', 'phone_code' => '+970', 'nationality' => 'Palestinian', 'language' => 'Arabic'],
    'PA' => ['name' => 'Panama', 'phone_code' => '+507', 'nationality' => 'Panamanian', 'language' => 'Spanish'],
    'PG' => ['name' => 'Papua new Guinea', 'phone_code' => '+675', 'nationality' => 'Papua New Guinean, Papuan', 'language' => 'English'],
    'PY' => ['name' => 'Paraguay', 'phone_code' => '+595', 'nationality' => 'Paraguayan', 'language' => 'Spanish'],
    'PE' => ['name' => 'Peru', 'phone_code' => '+51', 'nationality' => 'Peruvian', 'language' => 'Spanish'],
    'PH' => ['name' => 'Philippines', 'phone_code' => '+63', 'nationality' => 'Philippine, Filipino', 'language' => 'English'],
    'PN' => ['name' => 'Pitcairn Island', 'phone_code' => '+0', 'nationality' => 'Pitcairn Island', 'language' => 'English'],
    'PL' => ['name' => 'Poland', 'phone_code' => '+48', 'nationality' => 'Polish', 'language' => 'Polish'],
    'PT' => ['name' => 'Portugal', 'phone_code' => '+351', 'nationality' => 'Portuguese', 'language' => 'Portuguese'],
    'PR' => ['name' => 'Puerto Rico', 'phone_code' => '+1787', 'nationality' => 'Puerto Rican', 'language' => 'Spanish'],
    'QA' => ['name' => 'Qatar', 'phone_code' => '+974', 'nationality' => 'Qatari', 'language' => 'Arabic'],
    'RO' => ['name' => 'Romania', 'phone_code' => '+40', 'nationality' => 'Romanian', 'language' => 'Romanian'],
    'RU' => ['name' => 'Russia', 'phone_code' => '+70', 'nationality' => 'Russian', 'language' => 'Russian'],
    'RW' => ['name' => 'Rwanda', 'phone_code' => '+250', 'nationality' => 'Rwandan', 'language' => 'French'],
    'SH' => ['name' => 'Saint Helena', 'phone_code' => '+290', 'nationality' => 'Saint Helenian', 'language' => 'English'],
    'KN' => ['name' => 'Saint Kitts And Nevis', 'phone_code' => '+1869', 'nationality' => 'Kittitian or Nevisian', 'language' => 'Spanish'],
    'LC' => ['name' => 'Saint Lucia', 'phone_code' => '+1758', 'nationality' => 'Saint Lucian', 'language' => 'Spanish'],
    'PM' => ['name' => 'Saint Pierre and Miquelon', 'phone_code' => '+508', 'nationality' => 'Saint-Pierrais or Miquelonnais', 'language' => 'French'],
    'VC' => ['name' => 'Saint Vincent And The Grenadines', 'phone_code' => '+1784', 'nationality' => 'Saint Vincentian, Vincentian', 'language' => 'English'],
    'WS' => ['name' => 'Samoa', 'phone_code' => '+684', 'nationality' => 'Samoan', 'language' => 'English'],
    'SM' => ['name' => 'San Marino', 'phone_code' => '+378', 'nationality' => 'Sammarinese', 'language' => 'Italian'],
    'ST' => ['name' => 'Sao Tome and Principe', 'phone_code' => '+239', 'nationality' => 'São Toméan', 'language' => 'Portuguese'],
    'SA' => ['name' => 'Saudi Arabia', 'phone_code' => '+966', 'nationality' => 'Saudi, Saudi Arabian', 'language' => 'Arabic'],
    'SN' => ['name' => 'Senegal', 'phone_code' => '+221', 'nationality' => 'Senegalese', 'language' => 'French'],
    'RS' => ['name' => 'Serbia', 'phone_code' => '+381', 'nationality' => 'Serbian', 'language' => 'Serbian'],
    'SC' => ['name' => 'Seychelles', 'phone_code' => '+248', 'nationality' => 'Seychellois', 'language' => 'French'],
    'SL' => ['name' => 'Sierra Leone', 'phone_code' => '+232', 'nationality' => 'Sierra Leonean', 'language' => 'English'],
    'SG' => ['name' => 'Singapore', 'phone_code' => '+65', 'nationality' => 'Singaporean', 'language' => 'English'],
    'SK' => ['name' => 'Slovakia', 'phone_code' => '+421', 'nationality' => 'Slovak', 'language' => 'Slovak'],
    'SI' => ['name' => 'Slovenia', 'phone_code' => '+386', 'nationality' => 'Slovenian, Slovene', 'language' => 'Slovenian'],
    'SB' => ['name' => 'Solomon Islands', 'phone_code' => '+677', 'nationality' => 'Solomon Island', 'language' => 'English'],
    'SO' => ['name' => 'Somalia', 'phone_code' => '+252', 'nationality' => 'Somali, Somalian', 'language' => 'Arabic'],
    'ZA' => ['name' => 'South Africa', 'phone_code' => '+27', 'nationality' => 'South African', 'language' => 'English'],
    'GS' => ['name' => 'South Georgia', 'phone_code' => '+0', 'nationality' => 'South Georgia or South Sandwich Islands', 'language' => 'English'],
    'ES' => ['name' => 'Spain', 'phone_code' => '+34', 'nationality' => 'Spanish', 'language' => 'Spanish'],
    'LK' => ['name' => 'Sri Lanka', 'phone_code' => '+94', 'nationality' => 'Sri Lankan', 'language' => 'Sinhala'],
    'SD' => ['name' => 'Sudan', 'phone_code' => '+249', 'nationality' => 'Sudanese', 'language' => 'Arabic'],
    'SR' => ['name' => 'Suriname', 'phone_code' => '+597', 'nationality' => 'Surinamese', 'language' => 'Dutch'],
    'SZ' => ['name' => 'Swaziland', 'phone_code' => '+268', 'nationality' => 'Swazi', 'language' => 'English'],
    'SE' => ['name' => 'Sweden', 'phone_code' => '+46', 'nationality' => 'Swedish', 'language' => 'Swedish'],
    'CH' => ['name' => 'Switzerland', 'phone_code' => '+41', 'nationality' => 'Swiss', 'language' => 'Swiss'],
    'SY' => ['name' => 'Syria', 'phone_code' => '+963', 'nationality' => 'Syrian', 'language' => 'Arabic'],
    'TW' => ['name' => 'Taiwan', 'phone_code' => '+886', 'nationality' => 'Chinese, Taiwanese', 'language' => 'Chinese'],
    'TJ' => ['name' => 'Tajikistan', 'phone_code' => '+992', 'nationality' => 'Tajikistani', 'language' => 'Tajik'],
    'TZ' => ['name' => 'Tanzania', 'phone_code' => '+255', 'nationality' => 'Tanzanian', 'language' => 'English'],
    'TH' => ['name' => 'Thailand', 'phone_code' => '+66', 'nationality' => 'Thai', 'language' => 'Thai'],
    'TG' => ['name' => 'Togo', 'phone_code' => '+228', 'nationality' => 'Togolese', 'language' => 'French'],
    'TO' => ['name' => 'Tonga', 'phone_code' => '+676', 'nationality' => 'Tongan', 'language' => 'English'],
    'TT' => ['name' => 'Trinidad And Tobago', 'phone_code' => '+1868', 'nationality' => 'Trinidadian or Tobagonian', 'language' => 'English'],
    'TN' => ['name' => 'Tunisia', 'phone_code' => '+216', 'nationality' => 'Tunisian', 'language' => 'Arabic'],
    'TR' => ['name' => 'Turkey', 'phone_code' => '+90', 'nationality' => 'Turkish', 'language' => 'Turkish',],
    'TM' => ['name' => 'Turkmenistan', 'phone_code' => '+7370', 'nationality' => 'Turkmen', 'language' => 'Turkmen'],
    'TC' => ['name' => 'Turks And Caicos Islands', 'phone_code' => '+1649', 'nationality' => 'Turks and Caicos Island', 'language' => 'English'],
    'TV' => ['name' => 'Tuvalu', 'phone_code' => '+688', 'nationality' => 'Tuvaluan', 'language' => 'English'],
    'UG' => ['name' => 'Uganda', 'phone_code' => '+256', 'nationality' => 'Ugandan', 'language' => 'English'],
    'UA' => ['name' => 'Ukraine', 'phone_code' => '+380', 'nationality' => 'Ukrainian', 'language' => 'Ukrainian'],
    'AE' => ['name' => 'United Arab Emirates', 'phone_code' => '+971', 'nationality' => 'Emirati, Emirian, Emiri', 'language' => 'Arabic'],
    'GB' => ['name' => 'United Kingdom', 'phone_code' => '+44', 'nationality' => 'British, UK', 'language' => 'English',],
    'US' => ['name' => 'United States', 'phone_code' => '+1', 'nationality' => 'American', 'language' => 'English',],
    'UY' => ['name' => 'Uruguay', 'phone_code' => '+598', 'nationality' => 'Uruguayan', 'language' => 'Spanish'],
    'UZ' => ['name' => 'Uzbekistan', 'phone_code' => '+998', 'nationality' => 'Uzbekistani, Uzbek', 'language' => 'Uzbek'],
    'VU' => ['name' => 'Vanuatu', 'phone_code' => '+678', 'nationality' => 'Ni-Vanuatu, Vanuatuan', 'language' => 'English'],
    'VA' => ['name' => 'Vatican City State (Holy See)', 'phone_code' => '+39', 'nationality' => 'Vatican', 'language' => 'Italian'],
    'VE' => ['name' => 'Venezuela', 'phone_code' => '+58', 'nationality' => 'Venezuelan', 'language' => 'Spanish'],
    'VN' => ['name' => 'Vietnam', 'phone_code' => '+84', 'nationality' => 'Vietnamese', 'language' => 'Vietnamese'],
    'VG' => ['name' => 'Virgin Islands (British)', 'phone_code' => '+1284', 'nationality' => 'British Virgin Island', 'language' => 'English'],
    'VI' => ['name' => 'Virgin Islands (US)', 'phone_code' => '+1340', 'nationality' => 'U.S. Virgin Island', 'language' => 'English'],
    'WF' => ['name' => 'Wallis And Futuna Islands', 'phone_code' => '+681', 'nationality' => 'Wallis and Futuna, Wallisian or Futunan', 'language' => 'French'],
    'YE' => ['name' => 'Yemen', 'phone_code' => '+967', 'nationality' => 'Yemeni', 'language' => 'Arabic'],
    'ZM' => ['name' => 'Zambia', 'phone_code' => '+260', 'nationality' => 'Zambian', 'language' => 'English'],
    'ZW' => ['name' => 'Zimbabwe', 'phone_code' => '+263', 'nationality' => 'Zimbabwean', 'language' => 'English'],
];
